version: '3.8'

services:
  myapp:
    build: .
    volumes:
      - ./src:/app/src
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DISCORD_TOKEN=YOUR_DISCORD_TOKEN
      - DISCORD_USER_ID=YOUR_DISCORD_USER_ID
      - OPENAI_API_KEY=YOUR_OPENAI_API_KEY
